"""empty message

Revision ID: 1e4549a99da4
Revises: fa6355329968
Create Date: 2023-11-26 18:39:30.359477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e4549a99da4'
down_revision = 'fa6355329968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('article_title', sa.String(length=200), nullable=False),
                    sa.Column('article_content', sa.Text(), nullable=False),
                    sa.Column('article_time', sa.DateTime(), nullable=True),
                    sa.Column('article_author', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['article_author'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
